name: kgrs
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.10.18=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - colorama==0.4.6
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - idna==3.11
      - joblib==1.5.2
      - lightning-utilities==0.15.2
      - multidict==6.7.0
      - networkx==3.2.1
      - numpy==1.26.2
      - packaging==25.0
      - propcache==0.4.1
      - pytorch-lightning==2.1.0
      - pyyaml==6.0.3
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - threadpoolctl==3.6.0
      - timeout-decorator==0.5.0
      - torch==1.13.0
      - torchmetrics==1.5.2
      - tqdm==4.66.1
      - typing-extensions==4.15.0
      - yarl==1.22.0
prefix: D:\anaconda\envs\kgrs
